const actions = {
  SET_TITLE: "SET_TITLE",
  GET_IMAGES: "GET_IMAGES",
  IMAGES_LOAD_SUCCESS: "ADD_IMAGES",
  IMAGES_LOAD_ERROR: "ERROR",
  BADGE_COUNT: "SET_COUNT",
  CART_TOTAL: "SET_CART_TOTAL",
  ADD_TO_CART: "ADD_TO_CART",
  SET_MODAL_ID: "SET_ID",
  SORT_ASC: "LOW_TO_HIGH",
  SORT_DESC: "HIGH_TO_LOW",
  FILTER_BY_SIZE: "FILTER",
};

export default actions;
